import type { KeyBinding } from './types';

export const DEFAULT_BINDINGS: KeyBinding[] = [
  // -------------------------------------------------------------------------
  // App layer — Navigation
  // -------------------------------------------------------------------------
  {
    id: 'app.nav.row-up',
    layer: 'app',
    category: 'Navigation',
    description: 'Navigate row up',
    platform: 'both',
    key: 'ArrowUp',
    modifiers: { alt: true },
    action: 'navigateRow:up',
    global: true,
  },
  {
    id: 'app.nav.row-down',
    layer: 'app',
    category: 'Navigation',
    description: 'Navigate row down',
    platform: 'both',
    key: 'ArrowDown',
    modifiers: { alt: true },
    action: 'navigateRow:down',
    global: true,
  },
  {
    id: 'app.nav.column-left',
    layer: 'app',
    category: 'Navigation',
    description: 'Navigate column left',
    platform: 'both',
    key: 'ArrowLeft',
    modifiers: { alt: true },
    action: 'navigateColumn:left',
    global: true,
  },
  {
    id: 'app.nav.column-right',
    layer: 'app',
    category: 'Navigation',
    description: 'Navigate column right',
    platform: 'both',
    key: 'ArrowRight',
    modifiers: { alt: true },
    action: 'navigateColumn:right',
    global: true,
  },

  // -------------------------------------------------------------------------
  // App layer — Task reordering
  // -------------------------------------------------------------------------
  {
    id: 'app.task.reorder-left',
    layer: 'app',
    category: 'Tasks',
    description: 'Move active task left',
    platform: 'both',
    key: 'ArrowLeft',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'moveActiveTask:left',
    global: true,
  },
  {
    id: 'app.task.reorder-right',
    layer: 'app',
    category: 'Tasks',
    description: 'Move active task right',
    platform: 'both',
    key: 'ArrowRight',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'moveActiveTask:right',
    global: true,
  },

  // -------------------------------------------------------------------------
  // App layer — Task actions
  // -------------------------------------------------------------------------
  {
    id: 'app.task.close-shell',
    layer: 'app',
    category: 'Tasks',
    description: 'Close current shell',
    platform: 'both',
    key: 'w',
    modifiers: { cmdOrCtrl: true },
    action: 'closeShell',
    global: true,
  },
  {
    id: 'app.task.close',
    layer: 'app',
    category: 'Tasks',
    description: 'Close task',
    platform: 'both',
    key: 'W',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'closeTask',
    global: true,
  },
  {
    id: 'app.task.merge',
    layer: 'app',
    category: 'Tasks',
    description: 'Merge task',
    platform: 'both',
    key: 'M',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'mergeTask',
    global: true,
  },
  {
    id: 'app.task.push',
    layer: 'app',
    category: 'Tasks',
    description: 'Push task',
    platform: 'both',
    key: 'P',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'pushTask',
    global: true,
  },
  {
    id: 'app.task.new-shell',
    layer: 'app',
    category: 'Tasks',
    description: 'Spawn shell for task',
    platform: 'both',
    key: 'T',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'spawnShell',
    global: true,
  },
  {
    id: 'app.task.send-prompt',
    layer: 'app',
    category: 'Tasks',
    description: 'Send prompt',
    platform: 'both',
    key: 'Enter',
    modifiers: { cmdOrCtrl: true },
    action: 'sendPrompt',
    global: true,
  },

  // -------------------------------------------------------------------------
  // App layer — App shortcuts
  // -------------------------------------------------------------------------
  {
    id: 'app.new-terminal',
    layer: 'app',
    category: 'App',
    description: 'Create terminal',
    platform: 'both',
    key: 'D',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'createTerminal',
    global: true,
  },
  {
    id: 'app.new-task',
    layer: 'app',
    category: 'App',
    description: 'New task',
    platform: 'both',
    key: 'n',
    modifiers: { cmdOrCtrl: true },
    action: 'newTask',
    global: true,
  },
  {
    id: 'app.new-task-alt',
    layer: 'app',
    category: 'App',
    description: 'New task (alternate shortcut)',
    platform: 'both',
    key: 'a',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'newTask',
    global: true,
  },
  {
    id: 'app.toggle-sidebar',
    layer: 'app',
    category: 'App',
    description: 'Toggle sidebar',
    platform: 'both',
    key: 'b',
    modifiers: { cmdOrCtrl: true },
    action: 'toggleSidebar',
    // NOT global — only fires outside input/terminal
  },
  {
    id: 'app.toggle-help',
    layer: 'app',
    category: 'App',
    description: 'Toggle help dialog',
    platform: 'both',
    key: '/',
    modifiers: { cmdOrCtrl: true },
    action: 'toggleHelp',
    global: true,
    dialogSafe: true,
  },
  {
    id: 'app.toggle-help-f1',
    layer: 'app',
    category: 'App',
    description: 'Toggle help dialog (F1)',
    platform: 'both',
    key: 'F1',
    modifiers: {},
    action: 'toggleHelp',
    global: true,
    dialogSafe: true,
  },
  {
    id: 'app.toggle-settings',
    layer: 'app',
    category: 'App',
    description: 'Toggle settings dialog',
    platform: 'both',
    key: ',',
    modifiers: { cmdOrCtrl: true },
    action: 'toggleSettings',
    global: true,
    dialogSafe: true,
  },
  {
    id: 'app.close-dialogs',
    layer: 'app',
    category: 'App',
    description: 'Close dialogs',
    platform: 'both',
    key: 'Escape',
    modifiers: {},
    action: 'closeDialogs',
    dialogSafe: true,
    // NOT global
  },
  {
    id: 'app.reset-zoom',
    layer: 'app',
    category: 'App',
    description: 'Reset zoom',
    platform: 'both',
    key: '0',
    modifiers: { cmdOrCtrl: true },
    action: 'resetZoom',
    global: true,
  },

  // -------------------------------------------------------------------------
  // Terminal layer — Copy / Paste
  // -------------------------------------------------------------------------
  {
    id: 'term.copy',
    layer: 'terminal',
    category: 'Clipboard',
    description: 'Copy selection',
    platform: 'mac',
    key: 'c',
    modifiers: { meta: true },
    action: 'copy',
  },
  {
    id: 'term.copy-linux',
    layer: 'terminal',
    category: 'Clipboard',
    description: 'Copy selection (falls through to SIGINT when nothing is selected)',
    platform: 'linux',
    key: 'C',
    modifiers: { ctrl: true, shift: true },
    action: 'copy',
  },
  {
    id: 'term.paste',
    layer: 'terminal',
    category: 'Clipboard',
    description: 'Paste clipboard',
    platform: 'mac',
    key: 'v',
    modifiers: { meta: true },
    action: 'paste',
  },
  {
    id: 'term.paste-linux',
    layer: 'terminal',
    category: 'Clipboard',
    description: 'Paste clipboard (classic Windows / PowerShell style)',
    platform: 'linux',
    key: 'v',
    modifiers: { ctrl: true },
    action: 'paste',
  },
  {
    // Keep Ctrl+Shift+V too — Linux convention, dictation tools that
    // simulate pasting via that combo still work.
    id: 'term.paste-linux-shift',
    layer: 'terminal',
    category: 'Clipboard',
    description: 'Paste clipboard (Linux convention)',
    platform: 'linux',
    key: 'V',
    modifiers: { ctrl: true, shift: true },
    action: 'paste',
  },

  // -------------------------------------------------------------------------
  // Terminal layer — Special keys
  // -------------------------------------------------------------------------
  {
    id: 'term.shift-enter',
    layer: 'terminal',
    category: 'Editing',
    description: 'Send newline (Shift+Enter)',
    platform: 'both',
    key: 'Enter',
    modifiers: { shift: true },
    escapeSequence: '\x1b\r',
  },
  {
    id: 'term.home',
    layer: 'terminal',
    category: 'Editing',
    description: 'Move to beginning of line',
    platform: 'mac',
    key: 'ArrowLeft',
    modifiers: { meta: true },
    escapeSequence: '\x1b[H',
  },
  {
    id: 'term.end',
    layer: 'terminal',
    category: 'Editing',
    description: 'Move to end of line',
    platform: 'mac',
    key: 'ArrowRight',
    modifiers: { meta: true },
    escapeSequence: '\x1b[F',
  },
  {
    id: 'term.kill-line',
    layer: 'terminal',
    category: 'Editing',
    description: 'Kill line backward',
    platform: 'mac',
    key: 'Backspace',
    modifiers: { meta: true },
    escapeSequence: '\x15',
  },
];
