/**
 * assistant.ts
 * Backend support for the "Ask" sidebar — a regular Claude CLI we spawn in
 * a dedicated cwd so it can search across every saved chat.
 *
 * The cwd lives under Electron's userData dir and contains:
 *   - CLAUDE.md        — system-level instructions that teach the model
 *                        to answer with [[open:<uuid>]] markers.
 *   - SESSIONS-INDEX.md — a regenerated, compact index of every saved
 *                        session (id, date, project basename, title, desc).
 *
 * Generating the index on-demand is cheap: listSessions already caches
 * summaries in SQLite, so this is essentially a formatter.
 */

import { app } from 'electron';
import fs from 'fs';
import path from 'path';
import { listSessions } from './session-history.js';

const DIR_NAME = 'assistant';

function assistantDir(): string {
  const dir = path.join(app.getPath('userData'), DIR_NAME);
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

const CLAUDE_MD = `# ClaudeDesk "Ask" assistant

You live inside a sidebar of the ClaudeDesk app. The user already has many
past chats saved on disk. Your job is to help them **find** a chat and then
hand back a clickable button so they can jump straight into it.

## How the index works

A file next to this one, **SESSIONS-INDEX.md**, lists every chat the user has.
Each entry is one line:

\`\`\`
- <sessionId> · <date> · <projectBasename> · <title> — <first 240 chars of description>
\`\`\`

The file is regenerated by the app right before you read it, so whatever is
there is current. Read it with \`Read SESSIONS-INDEX.md\` (or \`cat\`) when
you need to look something up.

## Output contract — read carefully

When you name a chat the user should open, **always** wrap its full UUID in
this exact marker:

\`\`\`
[[open:11111111-2222-3333-4444-555555555555]]
\`\`\`

The ClaudeDesk UI parses that marker out of your response and renders a
clickable chip below the terminal — clicking it opens the chat. No marker →
no chip. Write the marker on the same line as the title so the chip lines
up with what you say about it.

Example reply:

> I found two chats about the login refactor:
> - "Update login.ts" — 2026-04-14 — [[open:abc12345-6789-abab-cdcd-ef0123456789]]
> - "Add refresh-token flow" — 2026-04-09 — [[open:def45678-9012-abab-cdcd-ef0987654321]]

## Scope rules

- Never guess UUIDs. Only emit ones you actually saw in SESSIONS-INDEX.md.
- If nothing matches, say so briefly — no marker.
- Don't open or modify anything outside this cwd. Don't run the user's chats.
- Keep replies tight: 1–2 lines per matching chat, then the marker.
`;

function ensureClaudeMd(dir: string): void {
  const file = path.join(dir, 'CLAUDE.md');
  // Only write if missing or changed — avoids bumping mtime on every open.
  try {
    const current = fs.readFileSync(file, 'utf-8');
    if (current === CLAUDE_MD) return;
  } catch {
    /* missing — fall through to write */
  }
  fs.writeFileSync(file, CLAUDE_MD, 'utf-8');
}

/** Plain-ASCII-safe compaction — index file is read by an LLM so keep it narrow. */
function clipOneLine(raw: string | undefined, limit: number): string {
  if (!raw) return '';
  return raw.replace(/\s+/g, ' ').trim().slice(0, limit);
}

function basename(p: string): string {
  return p.split(/[\\/]/).filter(Boolean).pop() ?? p;
}

async function writeSessionsIndex(dir: string): Promise<number> {
  const items = await listSessions();
  const lines = [
    '# ClaudeDesk sessions index',
    '',
    `Generated: ${new Date().toISOString()}`,
    `Total sessions: ${items.length}`,
    '',
    '| id | date | project | title | description |',
    '|----|------|---------|-------|-------------|',
  ];
  for (const s of items) {
    const title = clipOneLine(s.title, 80).replace(/\|/g, '\\|');
    const desc = clipOneLine(s.description, 240).replace(/\|/g, '\\|');
    lines.push(`| ${s.sessionId} | ${s.date} | ${basename(s.projectPath)} | ${title} | ${desc} |`);
  }
  lines.push('');
  fs.writeFileSync(path.join(dir, 'SESSIONS-INDEX.md'), lines.join('\n'), 'utf-8');
  return items.length;
}

/**
 * Ensures CLAUDE.md and SESSIONS-INDEX.md exist in the assistant cwd and
 * returns both the cwd path and the number of sessions indexed.
 */
export async function ensureAssistantCwd(): Promise<{ cwd: string; sessionsCount: number }> {
  const dir = assistantDir();
  ensureClaudeMd(dir);
  const sessionsCount = await writeSessionsIndex(dir);
  return { cwd: dir, sessionsCount };
}

/** Just rewrite the index (cheap) without touching CLAUDE.md. */
export async function refreshAssistantIndex(): Promise<{ sessionsCount: number }> {
  const dir = assistantDir();
  const sessionsCount = await writeSessionsIndex(dir);
  return { sessionsCount };
}
