/**
 * session-title.ts
 *
 * Pure helpers for deriving a meaningful session TITLE from JSONL
 * user messages.
 *
 * The problem: a session that was compacted/continued has, as its
 * FIRST user message, a system-injected boilerplate block:
 *
 *   "This session is being continued from a previous conversation
 *    that ran out of context. The summary below covers…"
 *
 * Taking that as the title gives every continued chat the same
 * useless name. Likewise, local-command caveat blocks and slash
 * command wrappers are noise, not titles. isNoiseUserText flags all
 * of these so the title resolver can skip to the first REAL user
 * prompt.
 */

// All patterns are ANCHORED to the start of the (trimmed) text. The
// boilerplate blocks always BEGIN with these phrases; unanchored
// matching swallowed real user prompts that merely MENTIONED a phrase
// mid-sentence (e.g. «сессия упала с ошибкой that ran out of context —
// разберись») — the user saw whole messages vanish from transcripts.
const NOISE_PATTERNS: RegExp[] = [
  // Claude Code compaction / continuation banner.
  /^this session is being continued from a previous conversation/i,
  // The summary preamble that sometimes leads on its own.
  /^the summary below covers the earlier portion of the conversation/i,
  // Local-command caveat wrappers injected by the CLI.
  /^caveat: the messages below were generated by the user/i,
  // Slash-command stdout wrappers with no real prose.
  /^<command-(name|message|args)>/i,
  /^<local-command-(stdout|stderr|caveat)>/i,
];

/**
 * First words of the prompt that session-summarize.ts sends to a
 * headless `claude -p` when generating AI titles. That helper run
 * leaves its own mini-JSONL in ~/.claude/projects — History must hide
 * those, and this prefix is how they are recognised. Shared from here
 * because session-history.ts ↔ session-summarize.ts would otherwise
 * import each other in a cycle.
 */
export const AI_TITLE_HELPER_PREFIX = 'Ниже фрагмент диалога пользователя с ассистентом';

/** True when a session's parsed title shows it is an AI-title helper
 *  run, not a real conversation. */
export function isAiTitleHelperText(text: string | null | undefined): boolean {
  return !!text && text.trimStart().startsWith(AI_TITLE_HELPER_PREFIX);
}

/**
 * True when the text is system/CLI boilerplate rather than a real
 * user instruction — i.e. it should NOT be used as a session title.
 */
export function isNoiseUserText(text: string): boolean {
  const t = text.trim();
  if (t.length === 0) return true;
  return NOISE_PATTERNS.some((re) => re.test(t));
}

/**
 * Pick the best title from an ordered list of user message texts.
 * Returns the first non-noise message, or — if every message is
 * noise (e.g. the session only contains a continuation banner so
 * far) — a generic fallback derived from the session id.
 */
export function pickSessionTitle(
  userTexts: string[],
  sessionId: string,
): { title: string; summary: string } | null {
  for (const raw of userTexts) {
    if (!raw) continue;
    if (isNoiseUserText(raw)) continue;
    return { title: raw.slice(0, 80), summary: raw.slice(0, 240) };
  }
  // Everything was noise — only return a fallback if we actually had
  // SOME text (so the caller can distinguish "no messages parsed yet"
  // from "all noise"). Caller passes [] → returns null.
  if (userTexts.length > 0) {
    return {
      title: `continued session ${sessionId.slice(0, 8)}`,
      summary: `Continued/compacted session — no fresh prompt yet (${sessionId.slice(0, 8)})`,
    };
  }
  return null;
}

/**
 * Heuristic used for cache-busting: does a stored title look like the
 * old boilerplate-derived title? If so we re-parse even when the file
 * mtime is unchanged, so previously-cached bad titles get healed.
 */
export function looksLikeStaleBoilerplateTitle(title: string | null | undefined): boolean {
  if (!title) return false;
  return isNoiseUserText(title);
}
