/* eslint-disable @typescript-eslint/no-non-null-assertion -- test fixtures index into known-shaped data */
/**
 * session-title.test.ts
 *
 * Pins the title-derivation so continued/compacted sessions stop
 * getting the useless "This session is being continued…" title.
 */

import { describe, it, expect } from 'vitest';
import {
  isNoiseUserText,
  pickSessionTitle,
  looksLikeStaleBoilerplateTitle,
} from './session-title.js';

const CONTINUATION =
  'This session is being continued from a previous conversation that ran out of context. ' +
  'The summary below covers the earlier portion of the conversation.';

describe('isNoiseUserText', () => {
  it('flags the continuation banner', () => {
    expect(isNoiseUserText(CONTINUATION)).toBe(true);
  });
  it('flags local-command caveat blocks', () => {
    expect(
      isNoiseUserText(
        'Caveat: The messages below were generated by the user while running local commands. DO NOT respond…',
      ),
    ).toBe(true);
  });
  it('flags slash-command wrappers', () => {
    expect(isNoiseUserText('<command-name>/model</command-name>')).toBe(true);
    expect(isNoiseUserText('<local-command-stdout>done</local-command-stdout>')).toBe(true);
  });
  it('flags empty/whitespace', () => {
    expect(isNoiseUserText('')).toBe(true);
    expect(isNoiseUserText('   ')).toBe(true);
  });
  it('does NOT flag a real prompt', () => {
    expect(isNoiseUserText('Fix the scroll bug in the terminal please')).toBe(false);
    expect(isNoiseUserText('Привет, помоги с обложкой для видео')).toBe(false);
  });
});

describe('pickSessionTitle', () => {
  it('skips continuation banner and uses the first real prompt', () => {
    const texts = [CONTINUATION, 'Add fork lineage to the history panel'];
    const picked = pickSessionTitle(texts, 'abcdef12-3456');
    expect(picked).not.toBeNull();
    expect(picked!.title).toBe('Add fork lineage to the history panel');
  });

  it('skips MULTIPLE noise blocks before the real prompt', () => {
    const texts = [
      CONTINUATION,
      '<command-name>/compact</command-name>',
      'Caveat: The messages below were generated by the user while running local commands.',
      'Restructure my folders please',
    ];
    const picked = pickSessionTitle(texts, 'deadbeef-0000');
    expect(picked!.title).toBe('Restructure my folders please');
  });

  it('returns a continued-session fallback when every message is noise', () => {
    const picked = pickSessionTitle([CONTINUATION], 'abcdef12-3456');
    expect(picked).not.toBeNull();
    expect(picked!.title).toMatch(/^continued session abcdef12/);
  });

  it('returns null for an empty list (no messages parsed)', () => {
    expect(pickSessionTitle([], 'abcdef12')).toBeNull();
  });

  it('truncates long prompts to 80/240 chars', () => {
    const long = 'x'.repeat(500);
    const picked = pickSessionTitle([long], 'id');
    expect(picked!.title.length).toBe(80);
    expect(picked!.summary.length).toBe(240);
  });
});

describe('looksLikeStaleBoilerplateTitle (cache-busting)', () => {
  it('true for a stored continuation-banner title', () => {
    expect(looksLikeStaleBoilerplateTitle(CONTINUATION.slice(0, 80))).toBe(true);
  });
  it('false for a normal title', () => {
    expect(looksLikeStaleBoilerplateTitle('Fix scroll bug')).toBe(false);
  });
  it('false for null/undefined', () => {
    expect(looksLikeStaleBoilerplateTitle(null)).toBe(false);
    expect(looksLikeStaleBoilerplateTitle(undefined)).toBe(false);
  });
});
